insert into categorie (id, nom) values (1, 'Painting & Vinyl Wall Covering');
insert into categorie (id, nom) values (2, 'Waterproofing & Caulking');
insert into categorie (id, nom) values (3, 'Elevator');
insert into categorie (id, nom) values (4, 'Hard Tile & Stone');
insert into categorie (id, nom) values (5, 'Elevator');
insert into categorie (id, nom) values (6, 'Masonry');
insert into categorie (id, nom) values (7, 'Doors, Frames & Hardware');
insert into categorie (id, nom) values (8, 'Roofing (Metal)');
insert into categorie (id, nom) values (9, 'Painting & Vinyl Wall Covering');
insert into categorie (id, nom) values (10, 'Overhead Doors');
insert into categorie (id, nom) values (11, 'Drilled Shafts');
insert into categorie (id, nom) values (12, 'EIFS');
insert into categorie (id, nom) values (13, 'Masonry');
insert into categorie (id, nom) values (14, 'Drywall & Acoustical (FED)');
insert into categorie (id, nom) values (15, 'Landscaping & Irrigation');
insert into categorie (id, nom) values (16, 'RF Shielding');
insert into categorie (id, nom) values (17, 'Ornamental Railings');
insert into categorie (id, nom) values (18, 'Curb & Gutter');
insert into categorie (id, nom) values (19, 'Wall Protection');
insert into categorie (id, nom) values (20, 'Waterproofing & Caulking');
insert into categorie (id, nom) values (21, 'Drywall & Acoustical (MOB)');
insert into categorie (id, nom) values (22, 'Ornamental Railings');
insert into categorie (id, nom) values (23, 'Retaining Wall and Brick Pavers');
insert into categorie (id, nom) values (24, 'Rebar & Wire Mesh Install');
insert into categorie (id, nom) values (25, 'Drilled Shafts');
insert into categorie (id, nom) values (26, 'Structural & Misc Steel Erection');
insert into categorie (id, nom) values (27, 'Structural and Misc Steel (Fabrication)');
insert into categorie (id, nom) values (28, 'Temp Fencing, Decorative Fencing and Gates');
insert into categorie (id, nom) values (29, 'Temp Fencing, Decorative Fencing and Gates');
insert into categorie (id, nom) values (30, 'Structural & Misc Steel Erection');
insert into categorie (id, nom) values (31, 'Site Furnishings');
insert into categorie (id, nom) values (32, 'Granite Surfaces');
insert into categorie (id, nom) values (33, 'Wall Protection');
insert into categorie (id, nom) values (34, 'Framing (Steel)');
insert into categorie (id, nom) values (35, 'Drilled Shafts');
insert into categorie (id, nom) values (36, 'Structural and Misc Steel (Fabrication)');
insert into categorie (id, nom) values (37, 'Masonry');
insert into categorie (id, nom) values (38, 'RF Shielding');
insert into categorie (id, nom) values (39, 'Granite Surfaces');
insert into categorie (id, nom) values (40, 'Overhead Doors');
insert into categorie (id, nom) values (41, 'Drilled Shafts');
insert into categorie (id, nom) values (42, 'Electrical and Fire Alarm');
insert into categorie (id, nom) values (43, 'Construction Clean and Final Clean');
insert into categorie (id, nom) values (44, 'Roofing (Metal)');
insert into categorie (id, nom) values (45, 'Casework');
insert into categorie (id, nom) values (46, 'Soft Flooring and Base');
insert into categorie (id, nom) values (47, 'Waterproofing & Caulking');
insert into categorie (id, nom) values (48, 'Hard Tile & Stone');
insert into categorie (id, nom) values (49, 'Electrical');
insert into categorie (id, nom) values (50, 'Overhead Doors');
insert into categorie (id, nom) values (51, 'Sitework & Site Utilities');
insert into categorie (id, nom) values (52, 'Fire Protection');
insert into categorie (id, nom) values (53, 'Site Furnishings');
insert into categorie (id, nom) values (54, 'Prefabricated Aluminum Metal Canopies');
insert into categorie (id, nom) values (55, 'HVAC');
insert into categorie (id, nom) values (56, 'Electrical');
insert into categorie (id, nom) values (57, 'Retaining Wall and Brick Pavers');
insert into categorie (id, nom) values (58, 'Retaining Wall and Brick Pavers');
insert into categorie (id, nom) values (59, 'Overhead Doors');
insert into categorie (id, nom) values (60, 'Drywall & Acoustical (MOB)');
insert into categorie (id, nom) values (61, 'Doors, Frames & Hardware');
insert into categorie (id, nom) values (62, 'Construction Clean and Final Clean');
insert into categorie (id, nom) values (63, 'Soft Flooring and Base');
insert into categorie (id, nom) values (64, 'Painting & Vinyl Wall Covering');
insert into categorie (id, nom) values (65, 'Sitework & Site Utilities');
insert into categorie (id, nom) values (66, 'EIFS');
insert into categorie (id, nom) values (67, 'Overhead Doors');
insert into categorie (id, nom) values (68, 'Hard Tile & Stone');
insert into categorie (id, nom) values (69, 'Termite Control');
insert into categorie (id, nom) values (70, 'Asphalt Paving');
insert into categorie (id, nom) values (71, 'Ornamental Railings');
insert into categorie (id, nom) values (72, 'Ornamental Railings');
insert into categorie (id, nom) values (73, 'Landscaping & Irrigation');
insert into categorie (id, nom) values (74, 'Casework');
insert into categorie (id, nom) values (75, 'Termite Control');
insert into categorie (id, nom) values (76, 'Marlite Panels (FED)');
insert into categorie (id, nom) values (77, 'Ornamental Railings');
insert into categorie (id, nom) values (78, 'Overhead Doors');
insert into categorie (id, nom) values (79, 'Epoxy Flooring');
insert into categorie (id, nom) values (80, 'Masonry');
insert into categorie (id, nom) values (81, 'Temp Fencing, Decorative Fencing and Gates');
insert into categorie (id, nom) values (82, 'Epoxy Flooring');
insert into categorie (id, nom) values (83, 'EIFS');
insert into categorie (id, nom) values (84, 'Fire Protection');
insert into categorie (id, nom) values (85, 'Structural & Misc Steel Erection');
insert into categorie (id, nom) values (86, 'Painting & Vinyl Wall Covering');
insert into categorie (id, nom) values (87, 'Drilled Shafts');
insert into categorie (id, nom) values (88, 'EIFS');
insert into categorie (id, nom) values (89, 'Fire Sprinkler System');
insert into categorie (id, nom) values (90, 'Sitework & Site Utilities');
insert into categorie (id, nom) values (91, 'Electrical and Fire Alarm');
insert into categorie (id, nom) values (92, 'Site Furnishings');
insert into categorie (id, nom) values (93, 'Painting & Vinyl Wall Covering');
insert into categorie (id, nom) values (94, 'Granite Surfaces');
insert into categorie (id, nom) values (95, 'Masonry');
insert into categorie (id, nom) values (96, 'Asphalt Paving');
insert into categorie (id, nom) values (97, 'Retaining Wall and Brick Pavers');
insert into categorie (id, nom) values (98, 'Doors, Frames & Hardware');
insert into categorie (id, nom) values (99, 'Asphalt Paving');
insert into categorie (id, nom) values (100, 'Plumbing & Medical Gas');
