insert into marque (id, nom) values (1, 'leader loperamide');
insert into marque (id, nom) values (2, 'IMOVAX RABIES');
insert into marque (id, nom) values (3, 'CAMBIA');
insert into marque (id, nom) values (4, 'Salicylic Acid');
insert into marque (id, nom) values (5, 'PREZISTA');
insert into marque (id, nom) values (6, 'Intermezzo');
insert into marque (id, nom) values (7, 'Lisinopril');
insert into marque (id, nom) values (8, 'Virt-Vite Plus');
insert into marque (id, nom) values (9, 'Pro-Den Rx');
insert into marque (id, nom) values (10, 'Pain Relief PM');
insert into marque (id, nom) values (11, 'Carvedilol');
insert into marque (id, nom) values (12, 'Famotidine');
insert into marque (id, nom) values (13, 'Ceftriaxone');
insert into marque (id, nom) values (14, 'Promethazine Hydrochloride');
insert into marque (id, nom) values (15, 'Labetalol Hydrochloride');
insert into marque (id, nom) values (16, 'Fast Results Genital Herpes Treatment');
insert into marque (id, nom) values (17, 'Aller-chlor');
insert into marque (id, nom) values (18, 'Dicloxacillin Sodium');
insert into marque (id, nom) values (19, 'Hoarse Cough');
insert into marque (id, nom) values (20, 'Extra Strength Rapid Release Acetaminophen PM');
insert into marque (id, nom) values (21, 'Zyvox');
insert into marque (id, nom) values (22, 'ETOPOPHOS');
insert into marque (id, nom) values (23, 'RISPERIDONE');
insert into marque (id, nom) values (24, 'Total White Brightening');
insert into marque (id, nom) values (25, 'Ampicillin and Sulbactam');
insert into marque (id, nom) values (26, 'Lovastatin');
insert into marque (id, nom) values (27, 'CARE ONE');
insert into marque (id, nom) values (28, 'Vitamin A and D');
insert into marque (id, nom) values (29, 'Reguloid');
insert into marque (id, nom) values (30, 'Salt Grass');
insert into marque (id, nom) values (31, 'Venlafaxine Hydrochloride');
insert into marque (id, nom) values (32, 'Simvastatin');
insert into marque (id, nom) values (33, 'Korres Wild Rose Mineral Foundation');
insert into marque (id, nom) values (34, 'Green Guard Maximum Non-Aspirin');
insert into marque (id, nom) values (35, 'Trixaicin');
insert into marque (id, nom) values (36, 'Bull Frog Kids Sunscreen 35');
insert into marque (id, nom) values (37, 'BULLFROG DEET FREE Mosquito Coast Sunscreen with Insect Repellent SPF 30');
insert into marque (id, nom) values (38, 'cough');
insert into marque (id, nom) values (39, 'ONE TOUCH ADVANCED TOPICAL ANESTHETIC');
insert into marque (id, nom) values (40, 'Hydrocodone Bitartrate And Acetaminophen');
insert into marque (id, nom) values (41, 'Hydromorphone Hydrochloride');
insert into marque (id, nom) values (42, 'Levothyroxine sodium');
insert into marque (id, nom) values (43, 'West Sycamore');
insert into marque (id, nom) values (44, 'Trifluridine');
insert into marque (id, nom) values (45, 'QUERCUS AGRIFOLIA POLLEN');
insert into marque (id, nom) values (46, 'Oxycodone and Acetaminophen');
insert into marque (id, nom) values (47, 'No7 Lifting and Firming Foundation Sunscreen SPF 15 Truffle');
insert into marque (id, nom) values (48, 'Aesculus e cort. 3');
insert into marque (id, nom) values (49, 'SUBSYS');
insert into marque (id, nom) values (50, 'oxycodone hydrochloride');
insert into marque (id, nom) values (51, 'Acetaminophen,Dextromethorphan,Doxylamine');
insert into marque (id, nom) values (52, 'No7 Protect and Perfect Skincare System Day Sunscreen SPF 15');
insert into marque (id, nom) values (53, 'safeHands');
insert into marque (id, nom) values (54, 'Ceftriaxone Sodium');
insert into marque (id, nom) values (55, 'Mefloquine Hydrochloride');
insert into marque (id, nom) values (56, 'bareMinerals 5-in-1 BB Advanced Performance Eyeshadow Broad Spectrum SPF 15');
insert into marque (id, nom) values (57, 'Xyzal');
insert into marque (id, nom) values (58, 'Enteric Coated Low Dose Aspirin');
insert into marque (id, nom) values (59, 'Extra Strength Pain Reliever');
insert into marque (id, nom) values (60, 'Smart Sense Childrens Mucus Relief');
insert into marque (id, nom) values (61, 'Arthritis Pain and Joint Relief');
insert into marque (id, nom) values (62, 'Acyclovir');
insert into marque (id, nom) values (63, 'FAMILY WELLNESS TRIPLE ANTIBIOTIC PLUS PAIN RELIEF');
insert into marque (id, nom) values (64, 'Antispetic');
insert into marque (id, nom) values (65, 'Nicorette');
insert into marque (id, nom) values (66, 'Valacyclovir Hydrochloride');
insert into marque (id, nom) values (67, 'Acne Wash Oil-Free');
insert into marque (id, nom) values (68, 'Prostate');
insert into marque (id, nom) values (69, 'Thioridazine Hydrochloride');
insert into marque (id, nom) values (70, 'Famotidine');
insert into marque (id, nom) values (71, 'Corlopam');
insert into marque (id, nom) values (72, 'Grass Smut Mixture');
insert into marque (id, nom) values (73, 'HZ');
insert into marque (id, nom) values (74, 'the Balm BalmShelter tinted moisturizer SPF 18 broad spectrum after dark');
insert into marque (id, nom) values (75, 'Lens Scale Pollen');
insert into marque (id, nom) values (76, 'Mango Blossom');
insert into marque (id, nom) values (77, 'Fentanyl Citrate');
insert into marque (id, nom) values (78, 'AILANTHUS ALTISSIMA POLLEN');
insert into marque (id, nom) values (79, 'Oat Grain');
insert into marque (id, nom) values (80, 'CASUARINA EQUISETIFOLIA POLLEN');
insert into marque (id, nom) values (81, 'Warfarin Sodium');
insert into marque (id, nom) values (82, 'RED ORANGE JELLY BB');
insert into marque (id, nom) values (83, 'Pollens - Trees, Tree Mix 11');
insert into marque (id, nom) values (84, 'citalopram hydrobromide');
insert into marque (id, nom) values (85, 'Meteoric Iron Phosphorus Quartz');
insert into marque (id, nom) values (86, 'COCHLIOBOLUS SATIVUS');
insert into marque (id, nom) values (87, 'Uramaxin');
insert into marque (id, nom) values (88, 'Zilactin-B');
insert into marque (id, nom) values (89, 'Lamisil');
insert into marque (id, nom) values (90, 'Abelmoschus');
insert into marque (id, nom) values (91, 'Aplicare Povidone-iodine Triples');
insert into marque (id, nom) values (92, 'Childrens Pain Relief');
insert into marque (id, nom) values (93, 'SUMATRIPTAN');
insert into marque (id, nom) values (94, '4 in 1 Pressed Mineral SPF 15 Deep');
insert into marque (id, nom) values (95, 'Warfarin Sodium');
insert into marque (id, nom) values (96, 'Geodon');
insert into marque (id, nom) values (97, 'LBEL REPLENISHING FOUNDATION SPF 14');
insert into marque (id, nom) values (98, 'Ciprofloxacin Hydrochloride');
insert into marque (id, nom) values (99, 'Mefloquine Hydrochloride');
insert into marque (id, nom) values (100, 'Clindamycin');
